baseURL = "https://shuppar.github.io/"
title = "Shivnarayan Dhuppar"
locale = "en-US"

[params]
  author = "Shivnarayan Dhuppar"
  description = "Postdoctoral researcher at MGH and the Broad Institute of MIT and Harvard"
  email = "sdhuppar@mgh.harvard.edu"
  googleScholar = "https://scholar.google.com/citations?hl=en&user=sYuB_dUAAAAJ"   # add your Google Scholar ID
  linkedin = "https://www.linkedin.com/in/shuppar"
  github = "shuppar"
  orcid = "/0000-0001-8772-1721"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "About"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Research"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "Activities"
  url = "/activities/"
  weight = 3

[[menu.main]]
  name = "Beyond Research"
  url = "/beyond/"
  weight = 4
